# Generated by Django 3.1.1 on 2021-01-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('todo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('todo_text', models.TextField()),
                ('todo_add_date', models.DateField()),
                ('todo_priporty', models.TextField(default='normal')),
                ('todo_add_time', models.TextField(default='0.0.0')),
                ('todo_updated_time', models.TextField(default='0.0.0')),
                ('author', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
