# Generated by Django 3.1.1 on 2021-01-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOS', '0002_todousermedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('task_notifications', models.BooleanField()),
                ('task_completedNotifiication', models.BooleanField()),
                ('via_email', models.BooleanField()),
                ('system_notifications', models.BooleanField()),
            ],
        ),
    ]
