# Generated by Django 3.1.1 on 2021-01-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOS', '0003_notificationssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationssettings',
            name='system_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationssettings',
            name='task_completedNotifiication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationssettings',
            name='task_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationssettings',
            name='via_email',
            field=models.BooleanField(default=False),
        ),
    ]
