# Generated by Django 3.1.1 on 2021-01-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOS', '0004_auto_20210116_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=50)),
                ('feedbackmessage', models.TextField()),
            ],
        ),
    ]
