# Generated by Django 3.1.1 on 2021-01-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOS', '0006_todos_todo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logins', models.IntegerField()),
                ('changeusername', models.IntegerField()),
                ('changepassword', models.IntegerField()),
                ('addtasks', models.IntegerField()),
                ('deletetasks', models.IntegerField()),
                ('edittasks', models.IntegerField()),
                ('completetask', models.IntegerField()),
                ('searchtask', models.IntegerField()),
            ],
        ),
    ]
