# Generated by Django 3.1.1 on 2021-01-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOS', '0008_insight_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='addtasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insight',
            name='changepassword',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insight',
            name='changeusername',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insight',
            name='completetask',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insight',
            name='deletetasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insight',
            name='edittasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insight',
            name='logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insight',
            name='searchtask',
            field=models.IntegerField(default=0),
        ),
    ]
