# Generated by Django 3.1.1 on 2021-01-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOS', '0009_auto_20210117_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='mostsearchkeywords',
            field=models.CharField(default='', max_length=50),
        ),
    ]
