# Generated by Django 3.1.1 on 2021-01-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOS', '0010_insight_mostsearchkeywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
