# Generated by Django 3.1.1 on 2021-01-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOS', '0011_insight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='mostsearchkeywords',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
