# Generated by Django 3.1.1 on 2021-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOS', '0012_auto_20210117_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='mostsearchkeywords',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
